---
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-demo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dharapvj.github.io/argocd-promotions-demo/
    chart: argo-demo-app
    targetRevision: 0.1.*
    path:
    # helm:
    #   valueFiles:
    #     - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  # syncPolicy:
  #   automated: null
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raw-k8s-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: raw-manifest/overlays/dev
    repoURL: 'https://github.com/dharapvj/argocd-promotions-demo'
    targetRevision: bgapp-dev
  project: default
  # syncPolicy:
  #   automated: null
