# Yellow App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellow
spec:
  template:
    spec:
      containers:
      - name: yellow
        env:
        - name: MESSAGE
          value: "This is a Stage App (raw yaml manifests)!!"
        - name: BGCOLOR
          value: "deeppink"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yellow-ing-raw
spec:
  rules:
    - http:
        paths:
          - path: /yellow-stage-raw(/.*)
            pathType: Prefix
            backend:
              service:
                name: yellow-svc
                port:
                  number: 3000