---
apiVersion: v1
kind: Namespace
metadata:
  name: stage

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-demo-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://dharapvj.github.io/argocd-promotions-demo/
    chart: argo-demo-app
    # A FIXED VERSION - IDEALLY FOR PRODUCTION
    targetRevision: 0.1.*
    helm:
      parameters:
        - name: ingressSuffix
          value: stage
        - name: appMessage
          value: "This is Stage App deployed via Helm!"
        - name: titlePrefix
          value: "helm - stage -"
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raw-k8s-stage
  namespace: argocd
spec:
  destination:
    namespace: stage
    server: 'https://kubernetes.default.svc'
  source:
    path: raw-manifest/overlays/stage
    repoURL: 'https://github.com/dharapvj/argocd-promotions-demo'
    targetRevision: bgapp-stage # this is a tag reference
  project: default
