---
apiVersion: v1
kind: Namespace
metadata:
  name: stage

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argo-demo-helm
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/dharapvj/flux-trial
#     targetRevision: HEAD
#     path: helm-chart
#     helm:
#       valueFiles:
#         - values.yaml
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: dev
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raw-k8s-stage
  namespace: argocd
spec:
  destination:
    namespace: stage
    server: 'https://kubernetes.default.svc'
  source:
    path: raw-manifest/
    repoURL: 'https://github.com/dharapvj/argocd-promotions-demo'
    targetRevision: bgapp-stage
  project: default
  syncPolicy:
    automated: null
