# Yellow App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yellow-app
  template:
    metadata:
      labels:
        app: yellow-app
    spec:
      containers:
      - name: yellow
        image: dharapvj/bgcolor-text-demo:1.0
        env:
        - name: MESSAGE
          value: "This is a Yellow App !!"
        - name: BGCOLOR
          value: "Khaki"
        ports:
          - name: http-port
            containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: yellow-svc
spec:
  type: ClusterIP
  ports:
    - port: 3000
  selector:
    app: yellow-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yellow-ing-raw
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: $1
spec:
  rules:
    - http:
        paths:
# Actual path definitions in overlays